/*
 * This source file was generated by the Gradle 'init' task
 */
package org.senegas.ledstrip.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LedStripAppTest {
    @Test void appHasAGreeting() {
        LedStripApp classUnderTest = new LedStripApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
