/*
 * This source file was generated by the Gradle 'init' task
 */
package org.senegas.ledstrip.app;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.senegas.ledstrip.domain.color.RgbColor;
import org.senegas.ledstrip.domain.led.LedStrip;
import org.senegas.ledstrip.domain.led.LedStripController;
import org.senegas.ledstrip.hardware.ConsoleLedStripHardwareAdapter;
import org.senegas.ledstrip.hardware.LedStripHardwareAdapter;

public class LedStripApp {

    public static String getGreeting() {
        return "__             _______ __       _       __\n"
                + "     / /   ___  ____/ / ___// /______(_)___  / /\n"
                + "    / /   / _ \\/ __  /\\__ \\/ __/ ___/ / __ \\/ / \n"
                + "   / /___/  __/ /_/ /___/ / /_/ /  / / /_/ /_/  \n"
                + "  /_____/\\___/\\__,_//____/\\__/_/  /_/ .___(_)   \n"
                + "                                   /_/          ";
    }
    public static final String TITLE = "LedStrip App";
    public static final String VERSION = "0.1.0";

    private static final Logger LOGGER = Logger.getLogger(LedStripApp.class.getName());

    public static void main(String[] args) {
        LOGGER.log(Level.INFO, getGreeting());
        LOGGER.log(Level.INFO, TITLE + " has started.");

        LedStrip strip = LedStrip.ofLength(16);
        LedStripHardwareAdapter adapter = new ConsoleLedStripHardwareAdapter();
        //RecordingAdapter adapter = new RecordingAdapter();

        LedStripController controller = new LedStripController(strip, adapter);

        controller.fill(RgbColor.WHITE);

        controller.setPixel(0, RgbColor.BLUE);
        controller.setPixel(5, RgbColor.GREEN);
        controller.setPixel(5, RgbColor.YELLOW);
        controller.togglePixel(5);

        controller.clear();
        //System.out.println("Last applied: " + adapter.last().orElse(null));
    }
}
