/*
 * This source file was generated by the Gradle 'init' task
 */
package org.senegas.ledstrip.app;


import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.formdev.flatlaf.FlatLightLaf;
import org.senegas.ledstrip.domain.color.RgbColor;
import org.senegas.ledstrip.domain.led.LedStrip;
import org.senegas.ledstrip.domain.led.LedStripController;
import org.senegas.ledstrip.hardware.ConsoleLedStripHardwareAdapter;
import org.senegas.ledstrip.hardware.LedStripHardwareAdapter;
import org.senegas.ledstrip.hardware.SwingLedStripHardwareAdapter;
import org.senegas.ledstrip.view.LedStripFrame;

import javax.swing.*;

public class LedStripApp {

    public static String getGreeting() {
        return "__             _______ __       _       __\n"
                + "     / /   ___  ____/ / ___// /______(_)___  / /\n"
                + "    / /   / _ \\/ __  /\\__ \\/ __/ ___/ / __ \\/ / \n"
                + "   / /___/  __/ /_/ /___/ / /_/ /  / / /_/ /_/  \n"
                + "  /_____/\\___/\\__,_//____/\\__/_/  /_/ .___(_)   \n"
                + "                                   /_/          ";
    }
    public static final String TITLE = "LedStrip App";
    public static final String VERSION = "0.1.0";

    private static final Logger LOGGER = Logger.getLogger(LedStripApp.class.getName());

    public static void main(String[] args) {
        LOGGER.log(Level.INFO, getGreeting());
        LOGGER.log(Level.INFO, TITLE + " has started.");

        EventQueue.invokeLater(() -> new LedStripApp().create());
    }

    private void create() {
        FlatLightLaf.setup();

        LedStrip strip = LedStrip.ofLength(32);

        final JFrame f = new LedStripFrame(strip);
        f.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        //f.setPreferredSize(new Dimension(350, 180));
        f.pack();
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }
}
